# NLP with Naive Bayes


In [ ]:
pylab inline

Populating the interactive namespace from numpy and matplotlib


In [ ]:
from sklearn.datasets import fetch_20newsgroups

In [ ]:
news = fetch_20newsgroups(subset='all')

In [ ]:
print(news.data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
print(type(news.data))

<class 'list'>


In [ ]:
print(type(news.target), type(news.target_names))

<class 'numpy.ndarray'> <class 'list'>


In [ ]:
print(news.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [ ]:
print(len(news.data))

18846


In [ ]:
print(len(news.target))

18846


In [ ]:
print(news.data[0])

From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!




In [ ]:
print(news.target[0], news.target_names[0])

10 alt.atheism


In [ ]:
split_perc = 0.75
split_size = int(len(news.data) * split_perc)
x_train = news.data[:split_size]
x_test= news.data[split_size:]
y_train = news.data[:split_size]
y_test= news.data[split_size:]

In [ ]:

from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer, HashingVectorizer, CountVectorizer



In [ ]:
clf_1 = Pipeline([
    ('vect', CountVectorizer()),
    ('clf', MultinomialNB()),
])

In [ ]:
clf_2 = Pipeline([
    ('vect', HashingVectorizer(alternate_sign=False)),
    ('clf', MultinomialNB()),
])

In [ ]:
clf_3 = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', MultinomialNB()),
])

In [ ]:
from sklearn.model_selection import cross_val_score, KFold
from scipy.stats import sem

In [ ]:
import numpy as np
def eval_cross_val(clf, x, y, k):
    cv = KFold(k, shuffle=True, random_state=0)
    scores = cross_val_score(clf, x, y, cv = cv)
    print (scores)
    return ("Mean scores: {0:.3f} ( +/- {1: .3f})").format(np.mean(scores), sem(scores))

In [ ]:
clfs = [ clf_1, clf_2, clf_3 ]
for clf in clfs:
    print(eval_cross_val(clf, news.data, news.target, 5))

[0.85782493 0.85725657 0.84664367 0.85911382 0.8458477 ]
Mean scores: 0.853 ( +/-  0.003)
[0.75517241 0.77659857 0.77076148 0.78508888 0.76200584]
Mean scores: 0.770 ( +/-  0.005)
[0.84482759 0.85990979 0.84558238 0.85990979 0.84213319]
Mean scores: 0.850 ( +/-  0.004)


In [ ]:
clf_4 = Pipeline([
    ('vect', TfidfVectorizer(
        token_pattern=r"\b[a-z0-9_\-\.]+[a-z][a-z0->>> 9_\-\.]+\b",
    )),
    ('clf', MultinomialNB())
])

In [ ]:
print(eval_cross_val(clf_4, news.data, news.target, 5))

[0.80450928 0.81029451 0.8113558  0.82143805 0.80817193]
Mean scores: 0.811 ( +/-  0.003)


In [ ]:
!touch stopwords_en.txt


In [ ]:
!echo "about,above,across,after,again,against,all,almost,alone,along,already,also,although,always,among,an,and,another,any,anybody,anyone,anything,anywhere,are,area,areas,around,as,ask,asked,asking,asks,at,away,b,back,backed,backing,backs,be,became,because,become,becomes,been,before,began,behind,being,beings,best,better,between,big,both,but,by,c,came,can,cannot,case,cases,certain,certainly,clear,clearly,come,could,d,did,differ,different,differently,do,does,done,down,down,downed,downing,downs,during,e,each,early,either,end,ended,ending,ends,enough,even,evenly,ever,every,everybody,everyone,everything,everywhere,f,face,faces,fact,facts,far,felt,few,find,finds,first,for,four,from,full,fully,further,furthered,furthering,furthers,g,gave,general,generally,get,gets,give,given,gives,go,going,good,goods,got,great,greater,greatest,group,grouped,grouping,groups,h,had,has,have,having,he,her,here,herself,high,high,high,higher,highest,him,himself,his,how,however,i,if,important,in,interest,interested,interesting,interests,into,is,it,its,itself,j,just,k,keep,keeps,kind,knew,know,known,knows,l,large,largely,last,later,latest,least,less,let,lets,like,likely,long,longer,longest,m,made,make,making,man,many,may,me,member,members,men,might,more,most,mostly,mr,mrs,much,must,my,myself,n,necessary,need,needed,needing,needs,never,new,new,newer,newest,next,no,nobody,non,noone,not,nothing,now,nowhere,number,numbers,o,of,off,often,old,older,oldest,on,once,one,only,open,opened,opening,opens,or,order,ordered,ordering,orders,other,others,our,out,over,p,part,parted,parting,parts,per,perhaps,place,places,point,pointed,pointing,points,possible,present,presented,presenting,presents,problem,problems,put,puts,q,quite,r,rather,really,right,right,room,rooms,s,said,same,saw,say,says,second,seconds,see,seem,seemed,seeming,seems,sees,several,shall,she,should,show,showed,showing,shows,side,sides,since,small,smaller,smallest,so,some,somebody,someone,something,somewhere,state,states,still,still,such,sure,t,take,taken,than,that,the,their,them,then,there,therefore,these,they,thing,things,think,thinks,this,those,though,thought,thoughts,three,through,thus,to,today,together,too,took,toward,turn,turned,turning,turns,two,u,under,until,up,upon,us,use,used,uses,v,very,w,want,wanted,wanting,wants,was,way,ways,we,well,wells,went,were,what,when,where,whether,which,while,who,whole,whose,why,will,with,within,without,work,worked,working,works,would,x,y,year,years,yet,you,young,younger,youngest,your,yours,z" > stopwords_en.txt

In [ ]:
!cat stopwords_en.txt

about,above,across,after,again,against,all,almost,alone,along,already,also,although,always,among,an,and,another,any,anybody,anyone,anything,anywhere,are,area,areas,around,as,ask,asked,asking,asks,at,away,b,back,backed,backing,backs,be,became,because,become,becomes,been,before,began,behind,being,beings,best,better,between,big,both,but,by,c,came,can,cannot,case,cases,certain,certainly,clear,clearly,come,could,d,did,differ,different,differently,do,does,done,down,down,downed,downing,downs,during,e,each,early,either,end,ended,ending,ends,enough,even,evenly,ever,every,everybody,everyone,everything,everywhere,f,face,faces,fact,facts,far,felt,few,find,finds,first,for,four,from,full,fully,further,furthered,furthering,furthers,g,gave,general,generally,get,gets,give,given,gives,go,going,good,goods,got,great,greater,greatest,group,grouped,grouping,groups,h,had,has,have,having,he,her,here,herself,high,high,high,higher,highest,him,himself,his,how,however,i,if,important,in,interest,interested,interes

In [ ]:
!sed -e's/,/\n/g' -i stopwords_en.txt

In [ ]:
!cat stopwords_en.txt

about
above
across
after
again
against
all
almost
alone
along
already
also
although
always
among
an
and
another
any
anybody
anyone
anything
anywhere
are
area
areas
around
as
ask
asked
asking
asks
at
away
b
back
backed
backing
backs
be
became
because
become
becomes
been
before
began
behind
being
beings
best
better
between
big
both
but
by
c
came
can
cannot
case
cases
certain
certainly
clear
clearly
come
could
d
did
differ
different
differently
do
does
done
down
down
downed
downing
downs
during
e
each
early
either
end
ended
ending
ends
enough
even
evenly
ever
every
everybody
everyone
everything
everywhere
f
face
faces
fact
facts
far
felt
few
find
finds
first
for
four
from
full
fully
further
furthered
furthering
furthers
g
gave
general
generally
get
gets
give
given
gives
go
going
good
goods
got
great
greater
greatest
group
grouped
grouping
groups
h
had
has
have
having
he
her
here
herself
high
high
high
higher
highest
him
himself
his
how
however
i
if
important
in
interest
interested
interes

In [ ]:
def get_stop_words():
    result = set ()
    for line in open('stopwords_en.txt', 'r').readlines():
        result.add(line.strip())
    return result

In [ ]:
from spacy.lang.de.stop_words import STOP_WORDS
clf_5 = Pipeline([
    ('vect', TfidfVectorizer(
        stop_words = list(get_stop_words()),
        token_pattern= r'\b[a-z0-9_\-\.]+[a-z][a-z0->>> 9_/-/.]+\b',
    )),
    ('clf', MultinomialNB()),
])

In [ ]:
print(eval_cross_val(clf_5, news.data, news.target, 5))

[0.80265252 0.81002919 0.81215176 0.8209074  0.81188644]
Mean scores: 0.812 ( +/-  0.003)


In [ ]:
clf_6 = Pipeline([
    ('vect', TfidfVectorizer(
        stop_words = list(get_stop_words()),
        token_pattern= r'\b[a-z0-9_\-\.]+[a-z][a-z0->>> 9_/-/.]+\b',
    )),
    ('clf', MultinomialNB(alpha=0.01)),
])

In [ ]:

print(eval_cross_val(clf_6, news.data, news.target, 5))

[0.84429708 0.85699124 0.85221544 0.86495092 0.85566463]
Mean scores: 0.855 ( +/-  0.003)


In [ ]:
from sklearn import metrics

def train_and_eval(clf, x_train, x_test, y_train, y_test):
    clf.fit(x_train, y_train)

    print("Accuracy on training set:")
    print(clf.score(x_train, y_train))
    print("Accuracy on testting set:")
    print(clf.score(x_test, y_test))

    y_pred = clf.predict(x_test)

    print("Classification Report")
    print(metrics.Classification_report(y_test, y_pred))
    print("confusion Matrix")
    print(metrics.confusion_matrix(y_test, y_pred))

In [ ]:
train_and_eval(clf_6, x_train, x_test, y_train, y_test)